### PR TITLE
added assembly 2022 card on homepage

### PR DESCRIPTION
**Pull request by gordoncc**
Added a new card right below the fold linking to the Assembly site.  Fixed some minor text styling issues
Screen Shot 2022-06-24 at 3 23 17 PM
.

### CODE REVIEW

**Comment by jalehman** [comment]
Nice, thanks for doing this. Going to wait to wait to merge for a few days to let everyone that got the notification via newsletter or UC post to have their shot at purchase.

**Comment by matildepark** [comment]
Please don’t commit husky back in, its styling on markdown content breaks markdoc tables on save.

**Comment by jalehman** [comment]
@gordoncc mind removing the husky commit so we can get this merged?

**Comment by matildepark** [comment]
Assemble

**Comment by gordoncc** [comment]
@jalehman @matildepark removed husky, i think we're good to go

**Pull request merged**
