### PR TITLE
Fix janky History section

### PR DESCRIPTION
**Pull request by noqcks**
Before 
image

After
image

Also changing History # from 3 -> 4.

### CODE REVIEW

**Comment by noqcks** [comment]
cc: @matildepark

**Comment by matildepark** [comment]
1. Hello! Thanks for the cc.
2. @msutherl is the stakeholder for urbit.org so they'll have to merge it.
3. Good catch on ToC.
4. This looks solid and consistent with the rest of the primer formatting, so I'm personally happy with this PR.

**Comment by flowerornament** [comment]
@noqcks thanks for this! Mind fixing `(5) Azimuth Distribution` as well while you're at it?

**Comment by noqcks** [comment]
@msutherl fixed

**Pull request merged**
