### PR TITLE
components: add card component, use for blogs

### LINKED ISSUE #1627: update blog post card designs on urbit.org to match blog post card on developers.urbit.org
Image

### PR DESCRIPTION
**Pull request by matildepark**
Fixes #1627

(Added these cards to FDS)

Sidebar — kinda wish we didn't have newsletter CTA on blog posts, it looks weird and pushy.

### CODE REVIEW

**Comment by gordoncc** [comment]
This is looking really good so far.

So, I know I said hold off on groups but I overlooked the fact that groups could be linked in the same way as apps.

So let's hold off on a groups index, but let's make them appear on organization pages the same way as applications.

**Comment by matildepark** [comment]
I think you meant to comment that on #1651

**Comment by gordoncc** [comment]
> This is looking really good so far.
> 
> So, I know I said hold off on groups but I overlooked the fact that groups could be linked in the same way as apps.
> 
> So let's hold off on a groups index, but let's make them appear on organization pages the same way as applications.

Lol yes

**Comment by gordoncc** [comment]
You're right about the newsletter c2a on the blog posts, it's a bit much – let's kill that for now.

The See More link no longer works now because there's an element from the card covering it.

Screen Shot 2022-07-20 at 4 32 15 PM

**Comment by matildepark** [comment]
It’s killed in the ecosystem PR

**Comment by matildepark** [comment]
Fixed the see more button

**Pull request merged**
