### PR TITLE
Remove stale ecosystem entries

### PR DESCRIPTION
**Pull request by ashelkovnykov**
Remove all groups, apps, marketplaces, and orgs to which the Urbit website should no longer link because they are either abandoned, defunct, broken, deleted, or otherwise inaccessible.

### CODE REVIEW

**Comment by sidnym-ladrut** [comment]
It probably is best to remove `%quorum` because it isn't currently working (not updated for 412k, nor updated for the `%groups` refactor), but the project hasn't been abandoned and will hopefully be restored in the next couple of months.

**Comment by pkova** [comment]
Don't remove `%canvas` my man.

**Comment by ashelkovnykov** [comment]
@yosoyubik `%canvas` not booting for me on two fresh comets - can you get a boot by copying the short code currently on the site into Grid?

**Comment by yosoyubik** [comment]
@ashelkovnykov my ~dister and ~picsel moons were down

**Comment by ashelkovnykov** [comment]
@yosoyubik Ammended

@hanfel-dovned Note that all of your apps don't install, currently

**Comment by ashelkovnykov** [comment]
@Fang- Note that `%picture` doesn't currently boot

**Comment by jalehman** [comment]
Going to go ahead and merge, further modifications can proceed in separate PRs. Thank you very much @ashelkovnykov !

**Pull request merged**
