### PR TITLE
Create membrane.md

### PR DESCRIPTION
**Pull request by thelifeandtimes**

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
@matildepark this looks like the deployment is failing, know if this has anything to do with recent markdoc changes?

**Comment by matildepark** [comment]
That hasn’t merged yet, so no.

**Review by jalehman — COMMENTED** [review]
Milestone #2 looks to be of about equivalent complexity as milestone #1, and as such I'd value it at two stars as well. 

However the bullet point **My spreadsheets expose an API that can be accessed by third-party front-ends, as well as other Urbit apps...** could be worth a star all of its own depending on exactly what this API is. How fine-grained is it? What's the interface like? A more detailed specification of what you mean here could be a good candidate for a milestone #3 worth another star (or as part of a future proposal) depending on the scope it entails.

**Review by mikeosborne — APPROVED** [review]

**Comment by thelifeandtimes** [comment]
@jalehman, ~tiller-tolbus provided an updated version which I just committed; further specification of API and inclusion of change management and conflicting changes reconciliation as a part of the scope.

**Comment by thelifeandtimes** [comment]
@jalehman nudge on your review on this?

**Review by jalehman — APPROVED** [review]

**Pull request merged**
