### PR TITLE
clarify what a breach is

### PR DESCRIPTION
**Pull request by galenwp**
it's true that 'breach' sounds like a security incident. updated the language here to clarify for people who have never seen urbit before.

### CODE REVIEW

**Comment by matildepark** [comment]
But no one calls it a reset? They call it a network-wide breach. You could just say "breached continuity" to be specific.

**Review by baudtack — CHANGES_REQUESTED** [review]
Agree with @matildepark continuity breach would be better.

**Comment by galenwp** [comment]
Everyone is going to think that anything with the word 'breach' in it is a security breach. Just went through this with someone else this morning.

Blockchain-based systems often do 'hard forks' or 'resets'. Feel free to suggest something that doesn't involve the word 'breach' on the frontpage, where someone may not already know inside-urbit terminology.

**Comment by vvisigoth** [comment]
We should merge this unless we get a better idea from @matildepark @baudtack that doessn't involve the term "breach."

You have until EOD to submit ideas.

**Comment by matildepark** [comment]
I don't have any, just hit the button

**Pull request merged**
