### PR TITLE
Banner Update (Software Distribution Copy)

### PR DESCRIPTION
**Pull request by urcades**
Updating the site's banner to highlight the latest major release on the network.

Copy is still pending review/editing.

### CODE REVIEW

**Comment by urcades** [comment]
@g-a-v-i-n Yowdy — I changed the one line of code that refers to the current banner's copy — I think we still need marcom peeps to edit the copy here though, just setting this up for a quick deploy.

Let me know if I changed the correct thing in the code!

**Comment by g-a-v-i-n** [comment]
Yep, looks good to me

**Comment by marisarow** [comment]
Can we update the color of the banner? Needs to change so that people know it's a new banner from our Assembly banner. 

For the copy: "PSA: New network update coming soon. Follow along @zodisok."

**Comment by urcades** [comment]
@marisarow copy is edited, changing the color of the link text is proving to be not as straightforward as I thought – @g-a-v-i-n , here's the styling of the banner component as I've currently edited it:

```
const Banner = ({ children, isOpen, href, dismiss }) => {
  return (
    <div className="w-full flex justify-center bg-blue-100">
      <SingleColumn>
        <div className="w-full layout">
          <div className="w-full  flex justify-between items-center px-4 md:px-8 py-4">
            <a href={href} target="_blank" className="text-blue-400">
              {children}
            </a>
            <button
              className="type-ui w-6 h-6 bg-blue-400 flex items-center justify-center rounded-full text-white hover:opacity-70"
              onClick={(e) => {
                e.stopPropagation();
                dismiss();
              }}
            >
              <Cross width="10" height="10" fill="#E5F7F1" />
            </button>
          </div>
        </div>
      </SingleColumn>
    </div>
  );
};
```

On the 7th line here, where I've edited `<a href={href} target="_blank" className="text-blue-400">`, it appears as though this isn't enough to override the default `green` color of our links. Lmk what i'm doing wrong here!

**Comment by g-a-v-i-n** [comment]
The banner isn't designed to contain links other than the one clicking the banner itself leads to - is there any way we can work with that constraint?

**Comment by urcades** [comment]
> The banner isn't designed to contain links other than the one clicking the banner itself leads to - is there any way we can work with that constraint?

Oh yeah, what I meant to say is that we're fine on the linking scheme (i just set the banner to link to the @zodisok twitter account), i'm just wondering how to fix this green text is all:

Screen Shot 2021-09-24 at 1 08 20 PM

I can't seem to figure out how to make the green text turn blue, for example

**Comment by g-a-v-i-n** [comment]
I will make it blue - any objections to dropping PSA? It's a banner so IMO that is redundant.

**Comment by urcades** [comment]
> I will make it blue - any objections to dropping PSA? It's a banner so IMO that is redundant.

Yeah, good call on dropping it, I support ya

**Comment by g-a-v-i-n** [comment]
What is the correct copy? Seeing 2 different things here and in the branch.

**Comment by g-a-v-i-n** [comment]
What address should the banner point to?

**Comment by urcades** [comment]
I literally just pushed the changes I had sitting locally, they should
match Marisa's copy added to this issue thread, sans the "PSA" as you
recommended

—
~fabled-faster
https://urbit.org/

**Comment by g-a-v-i-n** [comment]
Screen Shot 2021-09-24 at 12 15 19 PM

For future ref - the text-green-400 class on the inner element is overriding the blue on the outer element.

**Comment by g-a-v-i-n** [comment]
Not sure why this build is failing - looking into it.

**Comment by g-a-v-i-n** [comment]
I know what is wrong

**Comment by g-a-v-i-n** [comment]
why is god punishing me this way

**Review by g-a-v-i-n — APPROVED** [review]

**Comment by marisarow** [comment]
It's worth updating the banner now that the OTA is live. "Network update is live. Learn more at Assembly 2021." with a link to assembly.urbit.org.

**Comment by g-a-v-i-n** [comment]
Merged via #1178

**Pull request merged**
