### PR TITLE
Create interplanetary_commerce.md

### PR DESCRIPTION
**Pull request by bioy-casares**
New blog post

### CODE REVIEW

**Comment by tylershuster** [comment]
Dare I suggest using the new `web+urbitgraph://` links for the links to the channels at the end

**Comment by bioy-casares** [comment]
> Dare I suggest using the new `web+urbitgraph://` links for the links to the channels at the end

That sounds great- how would the link look?

[~pindet-timmut/urbitcoin-cash](web+urbitgraph://~pindet-timmut/urbitcoin-cash)

Like that?

**Comment by bioy-casares** [comment]
> > Dare I suggest using the new `web+urbitgraph://` links for the links to the channels at the end
> 
> That sounds great- how would the link look?
> 
> ~pindet-timmut/urbitcoin-cash
> 
> Like that?

oh it didn't render.  please describe

**Comment by tylershuster** [comment]
You might have to use `<a href="link here">Text</a>` syntax instead of markdown's `[Text](link here)` syntax but this:


`web+urbitgraph://group/~pindet-timmut/urbitcoin-cash`
and 
`web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~darrux-landes/business-building-on-urbit`

**Comment by tylershuster** [comment]
To be painfully clear, this is the final code: `[Urbitcoin Cash](web+urbitgraph://group/~pindet-timmut/urbitcoin-cash)` and if that doesn't work because it's a weird protocol, `<a href="web+urbitgraph://group/~pindet-timmut/urbitcoin-cash">Urbitcoin Cash</a>`

**Comment by bioy-casares** [comment]
Thanks Tyler!

**Comment by bioy-casares** [comment]
@tylershuster Links work.  Ready to merge.

**Pull request merged**
