### PR TITLE
Adding events to website

### PR DESCRIPTION
**Pull request by tylershuster**
For discussion with @jalehman as part of my work on the urbit.org overhaul

### CODE REVIEW

**Comment by tylershuster** [comment]
Changed pages include
```
/
/events
/events/*
```

This also changes the "page-indiced" sidebar behavior, hopefully at least somewhat better than the current version.

**Comment by tylershuster** [comment]
This also adds support for `pinned = true` on events, which will float them to the top of the homepage, and puts a gray background on the `/events` page.

**Comment by tylershuster** [comment]
https://user-images.githubusercontent.com/3999320/114072805-7f490280-9857-11eb-99c1-cf7ba85b2d45.mov

**Review by jalehman — COMMENTED** [review]
I'm getting the following when trying to run this, which is I think the same thing that the build server is choking on:

```
> export RUST_BACKTRACE=1; zola serve
Building site...
thread 'main' panicked at 'internal error: entered unreachable code: Got string in parse_basic_expression', /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.10/src/parser/mod.rs:268:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: std::panicking::begin_panic_fmt
   5: tera::parser::parse_basic_expression
   6: tera::parser::parse_macro_definition
   7: tera::parser::parse_content
   8: tera::template::Template::new
   9: tera::tera::Tera::load_from_glob
  10: tera::tera::Tera::parse
  11: site::Site::new
  12: zola::cmd::serve::create_new_site
  13: zola::cmd::serve::serve
  14: zola::main
  15: std::rt::lang_start::{{closure}}
  16: main
```

You wrote your work against Zola 0.8.0, right?

**Comment by tylershuster** [comment]
Yep

**Comment by jalehman** [comment]
Have you tried on a fresh build to see if you can reproduce this issue?

**Comment by tylershuster** [comment]
I realized I'm actually running 0.9.0. This seems related to https://github.com/getzola/zola/issues/748 which is patently unhelpful in its resolution

**Comment by tylershuster** [comment]
Has to do with this change: https://github.com/Keats/tera/commit/b53b693d80827b8be03966e132348d53f80a7d3e So something in macros

**Comment by tylershuster** [comment]
I emailed the developer to see if there's a hacky workaround we can use in the meantime.

**Comment by jalehman** [comment]
Thanks to @tomholford we've now gotten the site updated to zola version 0.13.0. There are a few changes needed to get this PR to build @tylershuster : 

*Remove the following files:*
- content/events/2017-03-23-after-hours-office-hours.md
-  content/events/2017-05-25-after-hours-office-hours.md
- content/events/2017-06-21-after-hours-office-hours.md
- content/events/2017-12-20-after-hours-its-just-a-party-man.md

*Update `templates/media/post.html`*
```
{% extends "base.html" %}
{% import "partials/pagination.html" as pagination %}
{% block title %}
  <meta name="og:title" content="{{ page.title }} - {{ config.title }}">
  <title>{{ page.title }} - {{ config.title }}</title>
{% endblock title %}
<...>
<article class="mb4 mt4 measure-wide full c4-12-lg">
    <h1 class="f5 fw6 mt0 mb1">{{ page.title }}</h1>
    {% if page.extra.author %}
    <span class="db">
      <span class="dib fw4 mr1" rel="author">{{ page.extra.author }}</span>
      {% if page.extra.ship %}
      <address class="dib gray0 fw4 mono">{{ page.extra.ship }}</address>
    {% endif %}
    </span>
    {% if page.date %}
      <time class="mono db gray0 f5">{{page.date | date(format="~%Y.%-m.%-d") }}</time>
    {% endif %}
    {% endif %}
    {% if page.extra.readtime %}
    <span class="dib mono {% if page.date %} ml2{% endif %} gray2 f5">{{ page.reading_time }}m read</span>
    {% endif %}

  {{ page.content | safe }}

  {{ pagination::pagination(page=page) }}
</article>
{% endblock content %}
```

**Review by jalehman — APPROVED** [review]
Aside from the changes in my previous comment, this is ready. 

I do have one request though: can we add a property for a Youtube link to each post, and do a video embed in place of an image if one exists?

**Comment by tylershuster** [comment]
What's up with this?
```
7:56:15 AM: zola
7:56:16 AM: Building site...
7:56:16 AM: Failed to build the site
7:56:16 AM: Error: Found path collisions:
7:56:16 AM: - `/docs/getting-started/contributing` from files ["docs/development/grants.md", "docs/development/develop.md"]
7:56:16 AM: - `/docs/using/creating-a-development-ship/` from files ["docs/development/develop.md", "docs/development/grants.md"]
```
I still fail to understand git submodules.

**Comment by jalehman** [comment]
Looks like these aliases need to go:
```
7:56:16 AM: - `/docs/getting-started/contributing` from files ["docs/development/grants.md", "docs/development/develop.md"]
7:56:16 AM: - `/docs/using/creating-a-development-ship/` from files ["docs/development/develop.md", "docs/development/grants.md"]
```

**Comment by jalehman** [comment]
> What's up with this?
> 
> ```
> 7:56:15 AM: zola
> 7:56:16 AM: Building site...
> 7:56:16 AM: Failed to build the site
> 7:56:16 AM: Error: Found path collisions:
> 7:56:16 AM: - `/docs/getting-started/contributing` from files ["docs/development/grants.md", "docs/development/develop.md"]
> 7:56:16 AM: - `/docs/using/creating-a-development-ship/` from files ["docs/development/develop.md", "docs/development/grants.md"]
> ```
> 
> I still fail to understand git submodules.

Ah—the docs submodule needs to not be included in the commits.

**Comment by jalehman** [comment]
Per Matilde: https://github.com/urbit/urbit.org/pull/588#issuecomment-817880654

**Comment by tylershuster** [comment]
Yes now I need to figure out how to do that

**Comment by tylershuster** [comment]
Looks good to me. I like the YouTube idea but I think we should wait on that so Ed can get the bitcoin page out

**Comment by tylershuster** [comment]
image

This is fine...right?

**Comment by jalehman** [comment]
> image
> 
> This is fine...right?

Hm...I'm not sure. Seems like we don't want the submodule deleted. That said, it seems like the deploy preview still works fine. @matildepark, halp?

**Comment by jalehman** [comment]
Can you just `git revert <hash>` on the commit that originally added the docs repo? I believe that hash is `d7eb1a9d6631a830988707c883d237cd704b4a97`

**Comment by tylershuster** [comment]
Ah this looks better.

**Comment by jalehman** [comment]
Any need to revert the one that removed the submodule also?

**Comment by tylershuster** [comment]
I had to resolve the conflict that developed because of that one

**Comment by tylershuster** [comment]
image

**Comment by jalehman** [comment]
🎉

**Comment by matildepark** [comment]
@tylershuster @jalehman Just for posterity:

I run a webhook on a VPS that listens for docs commits to master and auto-commits them here. It ensures that we are always on docs latest. So when people commit docs changes, it means their changes are behind, or they're making local-only docs changes that will be crushed by the next docs commit (that might conflict!).

As you're doing work on the site, you may think, "This experience sucks," and our predecessor agreed and wanted to merge the docs repo into the urbit.org repo. But that felt very convoluted for docs writers, and it made docs not portable at all should we ever want to ship the docs in some other form, so I effectively veto'd that. 

Our current solution works unless you're making huge changes site-wide. It's possible that our submodule borders are no longer workable if docs references urbit.org content and urbit.org references docs content and it breaks constantly. User manual content should then therefore be in the docs repo to prevent these cross-repo issues.

**Pull request merged**
