### PR TITLE
Markdown fixes

### PR DESCRIPTION
**Pull request by arthyn**
I think this fixes most of the problems with the markdown chain. Stated in this email:

<blockquote>
1. Section links are all prepended with user-content so urbit.org/foo#bar becomes urbit.org/foo#user-content-bar. This breaks all the links to sections throughout the docs. Issue: https://github.com/urbit/urbit.org/issues/1141

2) Tall-form codeblocks were rendering as though they were inline codeblocks. See issue https://github.com/urbit/urbit.org/issues/1139 - this was fixed in PR https://github.com/urbit/urbit.org/pull/1166 but as I understand it, it's a stop-gap fix that hasn't addressed the underlying cause.

3) Syntax highlighting's not working

4) search results for glossary.js entries acting weird, see https://github.com/urbit/urbit.org/issues/1185

5) there are various cases of html elements embedded in markdown files not rendering, eg images in html tags don't show. See https://github.com/urbit/urbit.org/issues/1160 for instance. The linked examples in the issue have been fixed by changing to markdown image embeds but it's still an issue and I think other html tag cases like eg https://github.com/urbit/urbit.org/issues/1153 have the same problem

6) html inside codeblocks is having bits of the tags stripped, see the html codeblock in
https://urbit-org-kta5u1772-urbit.vercel.app/docs/userspace/dist/guide#user-content-create-files-for-glob for example 
</blockquote>

Oof remark is hard to find information on. We have one remaining problem which is that fenced code blocks without a language spit out double escaped html entities like this(&#38;gt;) so we have to run an HTML decoder on all our markdown output which breaks blocks of HTML inside code fences like on tinnus-napbus' distribution guide.

The only solution I can think of is somehow give all our code blocks some default language like bash, find a quick way to do find and replace that won't screw everything up, or do it manually lol.

### CODE REVIEW

**Comment by g-a-v-i-n** [comment]
Amazing work.

My personal opinion is that we should steer away from HTML in markdown and handle the UX of Getting Started etc in a specific page designed for onboarding. Having HTML embedded in markdown is a convenient escape hatch but I strongly prefer not to rely on it going forward.

**Comment by arthyn** [comment]
That sounds like a good plan, then we could rip out the `allowdangerously` and `rehype-raw` stuff. We could also implement MDX if we want more advanced components like this in MD later on.

**Comment by g-a-v-i-n** [comment]
Cool. I would still like to keep the content we have that is currently using html but would like some kind of transition plan for it.

**Comment by jalehman** [comment]
@g-a-v-i-n is there anything preventing merging this? or is it good to go?

**Comment by g-a-v-i-n** [comment]
Looks fine to me, but might break HTML-in-markdown per Hunter's comment
above
—
~ridlur-figbud
https://urbit.org

**Comment by arthyn** [comment]
Oh sorry, HTML in markdown is fine, what I was referencing was HTML in code examples a la triple backticks. This PR actually fixes HTML in markdown so we get the nice tabs in stuff like the CLI install.

**Comment by g-a-v-i-n** [comment]
Awesome

**Pull request merged**
