### PR TITLE
add eyre-scry.md

### PR DESCRIPTION
**Pull request by ixv**
cc @liam-fitzgerald @belisarius222

### CODE REVIEW

**Comment by Fang-** [comment]
Notable prior art available here: urbit/urbit#4674

**Review by thelifeandtimes — COMMENTED** [review]
@ixv A few comments from the perspective of the foundation's grant program:
- Is this a proposal intended to be taken on by the ~tirrel team as a whole? assignee field is blank. Or is it a proposed bounty that you guys are speccing out and would like to see someone else take on and the foundation to help fund?
- Max proposal size at present is 5 stars, and ideally those map to milestones. I understand this may be a slightly different undertaking, but if the Eyre and Vere milestones are happening sequentially we should split them into two different proposals with more narrowly defined milestones. 
- If this is a proposal (as noted in the taxonomies) from ~tirrel, what would be the proposed delivery timeline?
- assuming notes under the implementation header are forthcoming?

**Comment by ixv** [comment]
- We're speccing it out and hoping that someone else will take it on who we will manage. Funding will come from our stipend as per our arrangement.

- I'm not totally opposed to splitting this into 2 proposals since they are atomic pieces of work that can go in separately, but given that the 2 parts of work are pretty closely intertwined in that the APIs for both are pretty much the same, it might be too much of a coordination burden.

- I would estimate 6 months total, or 3 months for each milestone. Will update the PR shortly.

- The implementation header is meant to include the milestones, ie: those are the 2 things that need to be implemented. I feel they have sufficient detail, but if you disagree I can probably write up some more.

**Comment by thelifeandtimes** [comment]
Ah, noted on the implementation header. Let's split into 2 grants so that we can line up the correct person and there is an additional 'carrot' for successful execution of phase 1 that they can then go take on phase 2, or if things aren't fully working out we can find the next contributor and have it be less messy. I'll also change to a bounty so we can list and start getting applicants (vs a proposal which would already have a specific contributor attached to it).

**Comment by thelifeandtimes** [comment]
@ixv @tacryt-socryp you guys going to split this into 2?

**Comment by thelifeandtimes** [comment]
@matildepark, know why this is breaking?

**Comment by matildepark** [comment]
> @matildepark, know why this is breaking?

Looks like it built to me.

**Review by mikeosborne — APPROVED** [review]

**Pull request merged**
