### PR TITLE
add geturbitid.com to install page

### PR DESCRIPTION
**Pull request by cxk280**
`geturbitid.com` was tested with positive feedback from several Tlon employees. At this point it also has several paying customers sourced elsewhere, none of whom have sent in any complaints. Spoke about this to @syzygyzer and he told me to go ahead and send the PR in.

### CODE REVIEW

**Comment by drbeefsupreme** [comment]
geturbitid is a different category of service from the others, since it provides hosting in addition to selling IDs. So I think you should put it on its own bullet point here.

We probably also want some kind of explanation of what hosting providers are somewhere, but I think that ought to be a separate PR that we can handle.

**Comment by tylershuster** [comment]
urth.systems offers a similar service to geturbitid and should probably be listed in the same category.

**Comment by matildepark** [comment]
I don't believe urth actually offers hosting.

**Comment by tylershuster** [comment]
You're right

**Comment by cxk280** [comment]
@syzygyzer I pushed up a change based on your comment. Should be ready to go now.

When you refer to the separate PR about what hosting is, does `we` mean Tlon employees?

**Comment by drbeefsupreme** [comment]
@cxk280 Yes, I meant Tlon employees (though of course anyone is welcome to submit such a PR, I'm just guaranteeing that myself or @baudtack will do it soon if nobody else does)

**Pull request merged**
