### PR TITLE
Update faq re: grants program

### PR DESCRIPTION
**Pull request by thelifeandtimes**
Was looking at old gifts, found this page and tossed some quick updates into it. Not sure what points to it, aside from navigating directly to https://urbit.org/faq.

### CODE REVIEW

**Comment by matildepark** [comment]
We kinda sorta retired it I think.

**Comment by gordoncc** [comment]
Oh, I pulled out the technical guides into Operators.  I thought I removed the file, maybe I just removed the link.

Is there any grants program info in here that we need to display or can we just erase this?

**Comment by matildepark** [comment]
This page is abandoned and outside the current IA, so we should just delete the page outright. Some of this content should be on the /grants page, maybe? But it seems kind of moot stuff ... maybe some mini-FAQ pages on the bounty pages.

**Comment by thelifeandtimes** [comment]
post assembly i'll take another look and move some of this content off into /grants somewhere. assuming we have no plans to revive the FAQ more broadly? dunno if it makes sense to more a bunch of this into a footer item for operators.urbit.org, developers.urbit.org, and urbit.org/grants or something like that?

**Comment by thelifeandtimes** [comment]
closing this out; grants page has been updated in a separate band.

**Pull request closed without merging**
