### PR TITLE
index.html: remove video lead

### PR DESCRIPTION
**Pull request by matildepark**
image

### CODE REVIEW

**Comment by galenwp** [comment]
Can we just like, give the line a bunch of padding on either side?

**Comment by matildepark** [comment]
`mt4` matches the header rhythm across the rest of urbit.org (compare on the [deploy preview](https://deploy-preview-464--urbit-org.netlify.app/)). How much padding you looking for?

**Comment by matildepark** [comment]
pong @galenwp

**Comment by urcades** [comment]
I can take over ~am, will set up the padding momentarily

—
~fabled-faster
https://urbit.org/

**Comment by urcades** [comment]
@matildepark I think it's ready to go. It's nice and dramatic, and nicely peeks at the description of urbit below on most mobile devices it seems. I'd be happy pushing it as-is.

**Pull request merged**
