### PR TITLE
site: grants navigation fixes

### LINKED ISSUE #1857: Search by grant directs to an invalid url
@matildepark the recent directory sorting to categorize grants by year while not changing the URL gets us an issue whereby if you `ctrl + K` search for a grant and follow that link, it will go to an invalid url that 404s. Looks like it is because it finds the `/2022` directory and attempts to put it in the URL.

### LINKED ISSUE #1858: Grants page filter ordering
@matildepark The recent change by directory seems like it now sorts grant cards at urbit.org/grants alphabetically. It would be preferable to have these sorted by date if possible.

### PR DESCRIPTION
**Pull request by matildepark**
Fixes #1858 
Fixes #1857 

I just _removed_ the alphabetical sort, let me know if this arranges as you'd expect or not. It seems to be newest first?

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
Looks like it does it by most recent month - day but oldest year?

**Comment by matildepark** [comment]
What do you want for "sort by date"? Reverse chronology?

**Comment by thelifeandtimes** [comment]
reverse chronology works.

**Comment by matildepark** [comment]
Give that a shot.

**Review by thelifeandtimes — APPROVED** [review]
lgtm

**Pull request merged**
