### PR TITLE
Search bar release

### PR DESCRIPTION
**Pull request by flowerornament**

### CODE REVIEW

**Comment by flowerornament** [comment]
Currently the sizing is completely messed up after the revert and merge from the `search-bar` branch.

**Comment by flowerornament** [comment]
Fixed the sizing – needed to divide the new rems by 4.

**Comment by flowerornament** [comment]
@francescanarea should we close this PR in favor of yours?

**Comment by francescanarea** [comment]
> @francescanarea should we close this PR in favor of yours?

@msutherl The only conflict here would be that mine does not exclude certain posts from search.  If this is a necessary feature, I could probably just merge post exclusion into mine.

**Comment by flowerornament** [comment]
@francescanarea contra our last conversation with Alex, I kind of like it – there's good content in the posts that's useful to have in search, even though it's a little confusing. Let's merge your work as is (when it's done) and we can remove later if desired.

**Comment by alexmatz** [comment]
for the record, I agree with Morgan, including posts is confusing. I prefer to merge as is and agree that we can integrate later if desired.

**Comment by msutherl** [comment]
@alexmatz looks like we got mixed up – I'm advocating for leaving search results for posts in, despite it being potentially confusing. The word "integrating" in my last sentence was confusing. Edited it to "remove".

@francescanarea there are some remaining issues here:

- Search pop-up doesn't work on Safari currently. Works fine on Chrome and Firefox
- Magnifying glass icon should be vertically centered
- Slashes are missing from titles with dates in them (test search term: "twitter")
- I think the light grey text is too light. People with bad eyesight won't be able to read it.

**Comment by msutherl** [comment]
Wait, I'm confused – I think I've been looking at the wrong branch here: https://github.com/urbit/urbit.org/pull/139. Investigating ...

**Comment by msutherl** [comment]
I have a few changes to merge and then this can be merged

**Comment by flowerornament** [comment]
@francescanarea ok, this look great, but it would be good to vertically center the glass icon. I tried and failed to find a way to do this, given how it's implemented. The rotation makes positioning difficult, and margins or padding seem to expand the box.

Screenshot 2019-07-20 20 34 48

**Comment by matildepark** [comment]
@msutherl @francescanarea Sorry about jumping in here -- I'm just sitting at the airport so it felt like it was worth a shot to see if I could patch that, so I put a PR in at #146.

**Comment by flowerornament** [comment]
Thanks @matildepark – not perfect, but better. I'll merge and we can address later.

**Pull request merged**
