### PR TITLE
20191106 Weekly(?) Update Post

### PR DESCRIPTION
**Pull request by urcades**
Adding a new post to the /updates page.

Would like some eyes on how links are displayed, copy, image selection, etc.

Related question: Do we have rules on how urls/links/copywriting is handled? I noticed urls were handed to me bare, but previous updates generally try and hide urls under 'normal' writing.

Please advise.

### CODE REVIEW

**Comment by crrncllns** [comment]
urls were in that format for a plain text email and i didn't change them - sorry

**Comment by urcades** [comment]
@collinscorrina Gotcha! It's no problem, was curious about how we go about that styling in general.

**Comment by galenwp** [comment]
This is definitely written in the style of an email update (which is plain text). I'm perfectly comfortable rephrasing all of this such that it actually uses [link](https://urbit.org)s

**Comment by crrncllns** [comment]
@urcades should be consistent with previous updates to that page. not sure what @galenwp has in mind.

**Comment by matildepark** [comment]
Following @galenwp's advice, amend the plaintext links to [links] and feel free to merge.

**Pull request merged**
