### PR TITLE
rewrite jar/jug examples to get rid of `mo`

### PR DESCRIPTION
**Pull request by drbeefsupreme**
Addresses #780

### CODE REVIEW

**Comment by ohAitch** [comment]
Should these also be `ly` instead of `limo`?

**Comment by drbeefsupreme** [comment]
What's the difference between them? I've been using them interchangeably.

```
++  le                                                ::  construct list
  |*  a=(list)
  ^+  =<  $
    |@  ++  $  ?:(*? ~ [i=(snag 0 a) t=$])
    --
  a

++  limo                                                ::  listify
  |*  a=*
  ^+  =<  $
    |@  ++  $  ?~(a ~ ?:(*? [i=-.a t=$] $(a +.a)))
    --
  a
```
I see that `+le` has a `list` as the sample, which seems circular? I also notice that they pretty print differently, and they are different nouns
```
> !=  (limo ~[1 2 3])
[8 [9 24.054 0 1.023] 9 2 10 [6 7 [0 3] 1 1 2 3 0] 0 2]
> !=  (ly ~[1 2 3])
[8 [9 3.062.778 0 1.023] 9 2 10 [6 7 [0 3] 1 1 2 3 0] 0 2]
```
but they're both described as producing a list from a null-terminated noun. Care to shed some light?

**Comment by ohAitch** [comment]
Oh I just meant to be consistent about shortname constructors
Looks like `le` calls out to snag while `limo` does "unify the types of all the elements" explicitly? The former seems like it should break if you pass an unfaced list, if it does idk why it's in the constructor section.

**Comment by drbeefsupreme** [comment]
Yeah I agree that using short name constructors for short name constructor examples is better stylistically.

**Pull request merged**
