### PR TITLE
Create seguro-prototype

### PR DESCRIPTION
**Pull request by thelifeandtimes**
for review by ~mastyr-bottec and @joemfb

### CODE REVIEW

**Comment by matthew-levan** [comment]
Thanks for getting this up @thelifeandtimes! Looks like it's not quite up to date with the Google doc though (overview section, a couple of sections in the performance section need deletion, and that's all).

**Comment by jfranklin9000** [comment]
Should be a `.md` file?

**Comment by thelifeandtimes** [comment]
@matthew-levan take a look now and then if it looks good @mikeosborne will merge.

**Comment by matthew-levan** [comment]
> @matthew-levan take a look now and then if it looks good @mikeosborne will merge.

Overview section is still outdated. It should read:

> Seguro improves Urbit's dependability by automatically replicating its event log across a set of machines in a cluster. The goal of this proposal is to write a working prototype of such a system. The prototype will be used to assess implementation direction and implement a complete integration.

Otherwise it looks good to me!

**Comment by thelifeandtimes** [comment]
@mikeosborne can you do final review and merge?

**Review by mikeosborne — APPROVED** [review]

**Pull request merged**
