### PR TITLE
Adds Ford runes to runes.js

### PR DESCRIPTION
**Pull request by drbeefsupreme**
This addresses #246 , but also needs @matildepark to adapt the search bar, and for the ford-headers branch to be merged in the docs repo for the links to work.

### CODE REVIEW

**Review by matildepark — APPROVED** [review]
LGTM. What should we change the keyboard shortcut to? Suggestions? @urcades ? @g-a-v-i-n ? `⌘/` is potentially nice, but is the Windows key / Meta key on non-Mac platforms, and less intuitive. We also don't mark a shortcut literally anywhere on the site. We could just strip the shortcut, but power users will appreciate one.

**Comment by Fang-** [comment]
imo only pressing escape should close the search bar (and return should go to the selected/first result).

**Comment by matildepark** [comment]
But what about _opening_ the search bar?

**Comment by Fang-** [comment]
That can remain unchanged just fine, right? Maybe I'm mistaken, but I feel "x to open, escape to close" is pretty common.

**Comment by matildepark** [comment]
So:

`/` to open
`esc` to close
`Enter` to hit first result

I think I can sneak this in today, then.

**Pull request merged**
