### PR TITLE
gall guide: fix broken link

### PR DESCRIPTION
**Pull request by ynx0**
userspage -> userspace

### CODE REVIEW

**Comment by ynx0** [comment]
Also I feel like the ToC from both https://urbit.org/docs/userspace/gall-guide and https://urbit.org/docs/userspace/gall-guide/intro should be sourced from a single file but idk if vercel has any functionality for that.

**Comment by drbeefsupreme** [comment]
Thanks!

**Comment by drbeefsupreme** [comment]
> Also I feel like the ToC from both https://urbit.org/docs/userspace/gall-guide and https://urbit.org/docs/userspace/gall-guide/intro should be sourced from a single file but idk if vercel has any functionality for that.

You can submit this as an issue.

**Comment by drbeefsupreme** [comment]
> Also I feel like the ToC from both https://urbit.org/docs/userspace/gall-guide and https://urbit.org/docs/userspace/gall-guide/intro should be sourced from a single file but idk if vercel has any functionality for that.

You can submit this as an issue.

**Pull request merged**
