### PR TITLE
added sortug organization

### PR DESCRIPTION
**Pull request by polwex**

### CODE REVIEW

**Comment by matildepark** [comment]
Both the URL and the image don't work.

**Comment by thelifeandtimes** [comment]
Feels weird to have so many ships listed?

**Comment by matildepark** [comment]
Why does it matter how many ships are listed? Those are used to check for applications and groups the org owns.

**Comment by thelifeandtimes** [comment]
ah, I see.

**Comment by polwex** [comment]
My apologies, the logo and website are fixed, should be working now.

**Review by thelifeandtimes — APPROVED** [review]
lgtm

**Pull request merged**
