### PR TITLE
Update grants.js

### PR DESCRIPTION
**Pull request by thomas-kroes**

### CODE REVIEW

**Comment by thomas-kroes** [comment]
@gordoncc I tried to play around and add the application deadlines in a suitable place. However as you see without success. Could you take a look at where to put the dates best and maybe the grants@urbit.org mail for questions?

**Comment by gordoncc** [comment]
@thomasurbit Do you really want to update the application deadlines every month?  It seems sufficient to say "bi-weekly"

**Comment by thomas-kroes** [comment]
I think it would be good for people to know when they can expect an answer. I'm happy to update that.

**Comment by gordoncc** [comment]
I'd manage expectations by saying you'll hear back within two to three weeks rather than giving specific operational details.

**Review by gordoncc — APPROVED** [review]

**Pull request merged**
