### PR TITLE
Create 2022-09-01-developer-future-of-khan.md

### PR DESCRIPTION
**Pull request by thomas-kroes**

### CODE REVIEW

**Review by jalehman — CHANGES_REQUESTED** [review]
Filename should be changed to remove the word holium and the % sign.

**Comment by thomas-kroes** [comment]
Done, that's what happens if you rush it.

**Comment by jalehman** [comment]
The filename needs to be changed, not the PR name. The filename becomes the URL.

**Comment by thomas-kroes** [comment]
argh, done.

**Comment by matildepark** [comment]
We should probably host this on media.urbit.org and not imgur — it's a little finnicky with hotlinks. @gordoncc ?

**Comment by thomas-kroes** [comment]
@matildepark I agree. @gordoncc told me to do that. I still don't have access to that storage, so I opt for the easiest possible route.

**Comment by jalehman** [comment]
Now you do

**Comment by thomas-kroes** [comment]
Thanks Josh, should be ready to merge now. @gordoncc we might want to look at the image again for the next one as the contrast with the grey text is not amazing.

**Review by jalehman — APPROVED** [review]

**Pull request merged**
