### PR TITLE
Update Milestone 3

### PR DESCRIPTION
**Pull request by niblyx-malnus**

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
@matildepark this is pending an additional milestone update from @niblyx-malnus who should have it for us shortly.

**Comment by matildepark** [comment]
Wasn't a push — I tend to filter things by "what needs my review" in the GitHub dashboard so I try to also ensure every issue has an "owner" so to speak.

**Comment by thelifeandtimes** [comment]
well... i took it as a shove + fighting words, soooo....

**Comment by thelifeandtimes** [comment]
superceded by #1826

**Pull request closed without merging**
