### PR TITLE
Update binary links to pull from new runtime repo

### PR DESCRIPTION
**Pull request by matthew-levan**
WIP until final filenames/URLs are confirmed.

See https://github.com/urbit/developers.urbit.org/pull/268 for similar `developers.urbit.org` changes.

### CODE REVIEW

**Comment by tinnus-napbus** [comment]
some formatting issues:

2023-01-13_17h00m42s

are we actually dropping windows support & adding an aarch64 macos build?

**Comment by mcevoypeter** [comment]
> some formatting issues:

Thanks for catching this. I believe I just addressed these.

> are we actually dropping windows support & adding an aarch64 macos build?

Yes, we are. Doing so was a part of extracting the runtime out of [urbit/urbit](https://github.com/urbit/urbit) into [its own repo](https://github.com/urbit/vere) and building with Bazel instead of Nix.

**Comment by jalehman** [comment]
Getting 404s on everything except the linux-aarch64 build.

**Comment by matthew-levan** [comment]
> Getting 404s on everything except the linux-aarch64 build.

All of the links in the Markdown (which will make it to the website) are actually redirects to GitHub links that won't be active until this PR is merged. For the redirect links, see `vercel.json`. I just tested the GH links and they work fine:
* https://github.com/urbit/vere/releases/latest/download/linux-aarch64.tgz 
* https://github.com/urbit/vere/releases/latest/download/linux-x86_64.tgz
* https://github.com/urbit/vere/releases/latest/download/macos-aarch64.tgz
* https://github.com/urbit/vere/releases/latest/download/macos-x86_64.tgz

**Comment by jalehman** [comment]
Right, I see that now. Thanks @matthew-levan !

**Comment by tinnus-napbus** [comment]
idk much about macos.. we still have a message about needing rosetta for the aarch64 build. Is that still correct? I thought rosetta let you run x86 on their m1/m2 aarch64 systems so it would be unnecessary now

**Comment by mcevoypeter** [comment]
The message about needing to run the `macos-aarch64` build under Rosetta is no longer necessary. The `macos-aarch64` binaries are now native AArch64 binaries:
```console
$ wget https://bootstrap.urbit.org/vere/live/v1.16/vere-v1.16-macos-aarch64
$ file vere-v1.16-macos-aarch64
vere-v1.16-macos-aarch64: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
t
```

**Pull request merged**
