### PR TITLE
fixes broken links

### PR DESCRIPTION
**Pull request by rmariani**
links of the `[text](/child/grandchild)` variety don't work in urbit.org/docs/. It treats that as `urbit.org/child/grandchild` instead of `urbit.org/docs/child/grandchild`

### CODE REVIEW

**Comment by flowerornament** [comment]
This checks in a /dist folder with a compiled copy of the website, which we don't want here

**Comment by rmariani** [comment]
Fixed

**Review by flowerornament — APPROVED** [review]
LGTM

**Comment by flowerornament** [comment]
Don't merge though please – I'll do it

**Review by flowerornament — CHANGES_REQUESTED** [review]
Don't want to check this dist folder into the git history – please review https://github.com/urbit/urbit.org/pull/64 instead

**Pull request closed without merging**
