### PR TITLE
removes incorrect information

### PR DESCRIPTION
**Pull request by rmariani**

### CODE REVIEW

**Comment by matildepark** [comment]
Seems fine. If we're going ahead with Chat CLI copy, does this mean we remove Hall from the Docs?

**Comment by rmariani** [comment]
Negative: https://boring-turing-42360d.netlify.com/docs/arvo/hall/

**Comment by matildepark** [comment]
I know it's there right now. It's that the Chat refactor, that this copy is seemingly amended for, will obsolesce Hall.

**Comment by rmariani** [comment]
Oh, right. Yeah I will just nuke that. I'll talk to @Fang-  about what should replaced it.

**Comment by matildepark** [comment]
This PR shouldn't touch docs, it should have another PR inside docs. I'll just approve this and merge for this part.

**Review by matildepark — APPROVED** [review]

**Comment by rmariani** [comment]
Yeah I misspoke

**Comment by Fang-** [comment]
Aww man, hall docs look great on the new website. Once hall gets completely removed, we'll have to remove the hall docs as obsolete. Think they should stay up until hall's _actually deleted_ instead of merely not-autostarted.

**Pull request merged**
