### PR TITLE
adding port beta notice to desktop app instructions

### PR DESCRIPTION
**Pull request by gordoncc**
getting lots of feedback from newbies that they can't connect to groups or install apps with port, need to manage expectations.

port notice

### CODE REVIEW

**Comment by matildepark** [comment]
I would be specific: it's really just Windows.

**Review by matildepark — COMMENTED** [review]
Don't we have `{% callout %}` for this?

**Comment by gordoncc** [comment]
Yea, but I wanted it to add in that yellow background.  Can I pass a class to the callout?

**Comment by matildepark** [comment]
The colour is hardcoded on the component right now, but we could always change that to just be a fallback. You can also use `{% div %}` here, but it seems moot. I'm just averse to introducing more inline html.

**Comment by matildepark** [comment]
My other qualm would be "does this introduce a contradiction to other copy in this section" — don't we recommend Port as a go-to? This is a bit of a mixed signal and might indicate a need to do something bigger here with the strategy.

**Comment by gordoncc** [comment]
Would be nice to be able to pass classname so we could have different types of callouts - alerts, heads up, etc - and have the gray as a fallback.

**Comment by gordoncc** [comment]
Yeah I'm with you on that qualm -- Port should be replaced by a pre-mined comet that you access in browser.  Wasn't @pkova working on something like this?

**Comment by matildepark** [comment]
Also "I can't install apps or join groups" smells like networking and/or networking keys issues to me. The thing where people get mysterious error message when they open ship in Windows is Port-specific but you know.

**Comment by matildepark** [comment]
Okay, try now. You can do `{% callout className="bg-yellow-200" %} Content content {% /callout %}`.

**Comment by matildepark** [comment]
It's working — but Tailwind is not adding the class to the CSS and detecting that it's there even though it does elsewhere. Let me see what I have to adjust.

**Comment by gordoncc** [comment]
Screen Shot 2022-08-29 at 8 25 35 PM

Relocated this warning but for some reason the background color doesn't show up here, but it does locally.  Is this an FDS issue or something like that?

**Comment by gordoncc** [comment]
Oh just saw your comment, you read my mind

**Comment by matildepark** [comment]
So we usually pass Markdown content into Markdoc to transform it first so Tailwind can see what a class is; but in this case because we aren't using FDS's custom components, the sections are skipped in the transform. Using FDS's renderer directly makes Tailwind upset in a way I don't currently understand. Removing the transform provides normal behaviour; I looked at other Markdoc injections of classes in the urbit.org codebase and they appear fine (when I would expect they wouldn't — like sure it knows what `className=""` is but why does it know `.font-bold` etc. in the inline declarations in Overview?). A little confused.

**Comment by gordoncc** [comment]
Is it ok to merge or should we do some more testing to make sure nothing is broken?

**Comment by matildepark** [comment]
I skimmed through all mentions of Markdoc components and it looked clean. We don't have that much content on urbit.org anymore.

**Comment by gordoncc** [comment]
Well, there's no rush, there's already a warning on the Windows section anyway so this is just styling.  Curious about the tailwind / fds issues.

**Comment by matildepark** [comment]
Kept the steps as is as before, but using FDS's parser instead of Markdoc's. This should produce least amount of potential failures, presumably, but again I looked at all our custom Markdoc calls with class declarations and they seem to be in place.

**Comment by gordoncc** [comment]
Let's go for it

**Review by matildepark — APPROVED** [review]

**Pull request merged**
