### PR TITLE
Hosting a meetup tips

### PR DESCRIPTION
**Pull request by rmariani**
Adds a page on best practices for hosting a meetup

### CODE REVIEW

**Review by matildepark — COMMENTED** [review]
This functions, but I wonder if this needs to be its own page, really. Why not just the bottom half of /meetups? If we use the page_indiced template it’ll be really clean and navigable too.

**Comment by rmariani** [comment]
I considered that, but the team and I think it's unwieldy. I am not against it as long as it's clean! How would that be done?

**Comment by matildepark** [comment]
I gave it a shot and you're right, it looks unwieldy. The best solution I found in my local environment is to make a /community/ directory and put the following pages in it:

- Hoon School
- Meetups
- Hosting a Meetup
- Governance

This matches the community IA to the other headings in the footer and gives it all a home to refer to instead of these two dangling meetup pages on our root directory.

I have this working if you're cool with me pushing it onto this branch and merging it all in.

**Comment by rmariani** [comment]
I'm fine with that. Thanks a lot!

**Review by matildepark — APPROVED** [review]

**Pull request merged**
