### PR TITLE
Added instructions for Windows via WSL 2

### PR DESCRIPTION
**Pull request by lukebuehler**
A few notes:
- Installing WSL 2 is a little tedious, but there should not be any major issues. Essentially it comes down to: registering for the Windows Insider Program, using Windows Update to get the latest "insider" version, installing WSL, and then upgrading WSL to WSL 2. All of this is described in the link in the text. WSL 2 is scheduled for release in Q2 2020 (of course, that date might slip a little now, but it will not be too long)
- WSL 2 is a really big change from WSL 1. The new version uses virtualization to host a real Linux kernel, and that's why Urbit works now. Essentially, it is the same as running Urbit in VirtualBox or VMWare, but the integration with Windows is much better.
- In the latest WSL 2 release, port forwarding is now automatically enabled, so Urbit feels quite "native" on Windows now. I've been running my planet for several days in the Ubuntu console now, but I'm browsing to landscape in Windows by simply going to localhost:8080.

### CODE REVIEW

**Comment by rmariani** [comment]
Thanks a lot! This is very useful.

But I am curious about the "officially supported" phraseology. What does it mean for us to "official support" a certain install method? That we give some guarantee that it won't cause problems on your up your machine? That we will respond to your issues? @jtobin @philipcmonk @belisarius222

**Comment by lukebuehler** [comment]
Sure, I'll let the the maintainers of this site decide how to phrase it, or if you want this disclaimer at all. @syzygyzer advised me to add this. Just let me know.
Previous discussion was here: https://github.com/urbit/docs/issues/842

**Comment by philipcmonk** [comment]
"Officially supported" doesn't mean anything specific, since we provide the software "as is".  However, I think the notice is good, since it suggests that most maintainers can't debug problems wiith it.

**Comment by ohAitch** [comment]
It at least helps to clarify that WSL1, the released one, is "officially
unsupported"

**Review by drbeefsupreme — CHANGES_REQUESTED** [review]
I think we should remove the line at the end about Visual Studio Code. It's surely useful information, but we don't talk about editors on this page since not everyone who uses Urbit is going to write code. It would be more appropriately placed [here](https://urbit.org/docs/tutorials/hoon/setup/#newbie-friendly-text-editors) I think.

**Comment by lukebuehler** [comment]
Thanks for the feedback. I'll get that done ASAP.

Maybe it could read: "Please note that this is more of an experimental way
of running Urbit, and we may not be able to assist you if you encounter
issues related to WSL 2, but these instructions have been tested and
verified for WSL 2 + Ubuntu 18.4 TSL."

I'll submit a separate pull request in the "Editors" section of the docs,
indicating that VS Code has WSL plugin.

**Comment by philipcmonk** [comment]
That sounds good to me.

**Comment by lukebuehler** [comment]
@ohAitch That WSL 1 is unsupported is explicitly mentioned in the second paragraph.

**Comment by rmariani** [comment]
LGTM

**Pull request merged**
