### PR TITLE
Refactor community/meetups page

### PR DESCRIPTION
**Pull request by mikeosborne**

### CODE REVIEW

**Comment by mikeosborne** [comment]
This is the branch where we are going to refactor the meetups page with the new bounty information and the live meetups snapshot

**Comment by mikeosborne** [comment]
@matildepark This current version seems to have lost all of @pkova's work. I don't have the git skills to re-merge his changes.

**Comment by mikeosborne** [comment]
disregard - we wanted to move the content that is in meetups.md to the /community root and I thought we already did that. What needs to be done to have that be the case?

**Comment by matildepark** [comment]
You put it here - https://github.com/urbit/urbit.org/blob/master/content/community/_index.md

**Comment by thelifeandtimes** [comment]
@mikeosborne what's the status on this?

**Comment by thelifeandtimes** [comment]
Do we want to do anything with this PR? @thomasurbit let's discuss tomorrow.

**Pull request closed without merging**
