### PR TITLE
Add Note on Nginx Configuration

### PR DESCRIPTION
**Pull request by Sneagan**
The web client requires constant refreshes to receive new messages without these settings in an Nginx reverse proxy.

### CODE REVIEW

**Review by baudtack — COMMENTED** [review]
I don't know anything about running urbit behind nginx. @vvisigoth any idea who might? Just want a second verification that this is correct.

**Comment by Fang-** [comment]
Long-standing advice for fixing nginx sse shenanigans has been to follow [this StackOverflow advice](https://stackoverflow.com/a/13673298/1334324).

@Sneagan (sorry for the wait on this and) the PR here mentions only three of those. I'm assuming you're running a standard nginx setup, so does that make the explicit `Connection` header and http version optional, as far as landscape behavior is concerned? Just making sure we're not leaving anything important out.

Might also be worth mentioning, super briefly, that this goes into the `location` block in your nginx config.

**Comment by baudtack** [comment]
Bump.

**Comment by baudtack** [comment]
@vvisigoth Do you know who might have the nginx knowledge to review and verify that this pr is technically correct?

**Comment by baudtack** [comment]
@brendanhay Do you happen to have any insight into nginx to tell if this pr is technically sound?

**Comment by brendanhay** [comment]
@baudtack LGTM

**Pull request merged**
