### PR TITLE
Update simple-durable-yours.md

### PR DESCRIPTION
**Pull request by crrncllns**
copyedits @galenwp. i'd also really suggest deleting "A home you don’t own is just a hotel room."

### CODE REVIEW

**Comment by crrncllns** [comment]
something wrong here too @matildepark

**Comment by matildepark** [comment]
Fixed the one mixed content link in the branch. I fixed it a few days ago but it was, for whatever reason, back to being mixed.

**Comment by crrncllns** [comment]
thanks...

**Comment by galenwp** [comment]
oxford commas everywhere — lgtm

**Pull request merged**
