### PR TITLE
dec spotlight, attempted to add groups functionality to ecosystem

### PR DESCRIPTION
**Pull request by gordoncc**
hey @matildepark – could please help me add in groups as something that can be featured in the Spotlight?

### CODE REVIEW

**Comment by gordoncc** [comment]
oh, @matildepark if you're not working this week then don't worry

**Comment by matildepark** [comment]
I'm here! I'm here!

**Comment by matildepark** [comment]
There's a lot of dangling imports and the like we could probably centralise and componentise here, I can pick at it a little later to simplify this maybe.

**Comment by gordoncc** [comment]
Thanks @matildepark !

**Comment by gordoncc** [comment]
Oh I'm seeing the index cards are behaving well, but the spotlight itself isn't recognizing the UF group
Screen Shot 2022-11-29 at 4 31 21 PM

**Comment by gordoncc** [comment]
Ok I figured it out.

**Comment by matildepark** [comment]
> Ok I figured it out.

Confusingly, that line in question *was* in https://github.com/urbit/urbit.org/pull/1918/commits/d8ebcba2e2c9a6545b1a4dc11d00f185893755c3, and dropped in the subsequent commits.

**Review by matildepark — APPROVED** [review]
lgtm

**Pull request merged**
