### PR TITLE
add overview page

### LINKED ISSUE #1632: Overview Section

### PR DESCRIPTION
**Pull request by matildepark**
Fixes #1632

Adds the revisions to the Understanding Urbit guide, the renaming to Overview, a new template with its own variant of the sidebar for the Overview section, new assets when necessary. Bumps foundation-design-system twice over — once for a `div` Markdoc component so we can two-up in Markdoc; and again for adding Network Explorer to the intranav.

The homepage's width and spacing is starting to get weird; I suspect @gordoncc wants to widen up the homepage but we have to do it in tandem with FDS; the intranav is meant to pair with our header width, so if we widen the header here, we have to do it everywhere. I'd rather do it uniformly as its own pass on all sites, so I try to make our amendments to the homepage fit the current width and spacing, while still widening the hero as per previous PRs.

### CODE REVIEW

**Comment by gordoncc** [comment]
Looking pretty good.  Can we make the font weight on the body subheadings a little bolder, and can we add an additional blank line or more padding per the designs to get more space between subsections?  Can we use multiple` <brs>` in markdown or maybe a styled `<hr>`?

Screen Shot 2022-07-13 at 10 53 00 AM
Screen Shot 2022-07-13 at 10 52 32 AM

**Comment by matildepark** [comment]
idk, let me try ...

**Comment by gordoncc** [comment]
Screen Shot 2022-07-13 at 11 00 56 AM
Screen Shot 2022-07-13 at 11 00 38 AM
The accented text should be bolder here too.

**Comment by matildepark** [comment]
OK, how's that? BTW, check out https://github.com/urbit/urbit.org/pull/1633/commits/4405ef28d7b7301854a7f2988307ef37003ae8bd, it's cool you can just add Tailwind wherever now.

**Comment by gordoncc** [comment]
Very cool on embedding tailwind in markdown.

Typography is looking good, something happened to one of the flexbox image layouts though.

Screen Shot 2022-07-13 at 11 33 44 AM

**Comment by matildepark** [comment]
@gordoncc It was a stale build cache. Try now — also fixed two issues on mobile in the process ...

**Review by gordoncc — APPROVED** [review]
totally forgot mobile, thanks for tackling.  looking good to me.

**Pull request merged**
