### PR TITLE
pages: add decentralized-discord landing page

### PR DESCRIPTION
**Pull request by matildepark**

### CODE REVIEW

**Comment by gordoncc** [comment]
Looks like the video playback isn't working on mobile unless there's some trick I'm not aware of

**Comment by matildepark** [comment]
[Turns out](https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari):

> Video elements that include `<video autoplay>` play automatically when the video loads in Safari on macOS and iOS, only if those elements also include the playsinline attribute.

**Comment by gordoncc** [comment]
Nice, playback working for me now.  Is there a way to make it loop or would we need gif technology for that

**Comment by gordoncc** [comment]
Ok, I'd just like to get a custom opengraph card image in and we're good to deploy:

https://storage.googleapis.com/media.urbit.org/site/landing/discord-opengraph.png

**Comment by matildepark** [comment]
image

**Review by gordoncc — APPROVED** [review]
Thanks!

**Pull request merged**
