### PR TITLE
allow code blocks in docs to expand wider

### LINKED ISSUE #605: main text area of docs is too narrow
The main text area column thingy is extremely narrow. This results in wrapping of a lot of codeblocks which makes them difficult to read.

Eg:

2021-04-23_11h44m53s

Something approximately like this would be better:

2021-04-23_11h51m44s

### PR DESCRIPTION
**Pull request by tylershuster**
image

Fixes https://github.com/urbit/urbit.org/issues/605

### CODE REVIEW

**Comment by matildepark** [comment]
There’s a few docs templates actually. Check chapters and sections

**Comment by tylershuster** [comment]
@matildepark ?

**Comment by matildepark** [comment]
Right, my main reservation was the choice to constrict this was a design one, but I don't know who design point even is on urbit.org anymore.

@urcades any preference?

https://deploy-preview-608--urbit-org.netlify.app/docs/hoon/hoon-school/ackermann/

**Comment by tylershuster** [comment]
@urcades

**Comment by drbeefsupreme** [comment]
Merging this per @jalehman 's request

**Pull request merged**
