### PR TITLE
redirect from takeover to week

### PR DESCRIPTION
**Pull request by jalehman**
Ideally the URL of the group should match the name of the group. This should be fine?

### CODE REVIEW

**Comment by matildepark** [comment]
I agree, it should. This will redirect to a 404 though, you need to actually rename the file too.

**Comment by jalehman** [comment]
I did, right? https://github.com/urbit/urbit.org/blob/dcec828da50302fdf59493677fccaab58e588d2f/content/groups/~ladtem-filmyr/urbit-ny-week.md

**Comment by matildepark** [comment]
The file says ny-week.md and the redirect is to nyc-week.md. Which one is canonical?

**Comment by jalehman** [comment]
Alright, third try's the charm.

**Review by matildepark — APPROVED** [review]

**Pull request merged**
