### PR TITLE
Create seguro-phase-2.md

### PR DESCRIPTION
**Pull request by thelifeandtimes**
@joemfb can you confirm that this scope looks good?

@mikeosborne can you confirm the meta tags and everything are looking good?

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
@matildepark any insight as to why this deployment is failing?

**Review by mikeosborne — COMMENTED** [review]
Looks good. Are all the deliverables going to me a single milestone for 5 stars?

**Comment by joemfb** [comment]
LGTM

**Review by mikeosborne — APPROVED** [review]

**Comment by joemfb** [comment]
@mikeosborne that's right, all the deliverables together from a single milestone.

**Pull request merged**
