### PR TITLE
Add value articles bounty

### PR DESCRIPTION
**Pull request by mikeosborne**

### CODE REVIEW

**Review by thelifeandtimes — CHANGES_REQUESTED** [review]
Need to change comp on this to 5,000 USD

**Review by thelifeandtimes — APPROVED** [review]
looks good.

**Review by thelifeandtimes — APPROVED** [review]

**Comment by thelifeandtimes** [comment]
Seems like I don't have write access; @mikeosborne go ahead and merge this.

**Comment by matildepark** [comment]
> At least 1 approving review is required **by reviewers with write access**.

lol. I'll merge

**Pull request merged**
