### PR TITLE
Update getting started documentation

### PR DESCRIPTION
**Pull request by leobauza**
This PR changes the getting started documentation to make it easier to get started. It also fixes some errors.

I had a hard time getting set up and I think this makes things clearer. I wonder if there are plans (or if tickets can be added) to document a broad overview of the sites structure to make it easier to contribute.

### CODE REVIEW

**Comment by flowerornament** [comment]
Thanks @leobauza! These changes are great. We don't have plans to make it easier to contribute to the site right now since there's been little interest and we also plan to overhaul the site again in 2019, but I'll be working on some fixes over the next few months and I could use all the help I can get.

Feel free to create an issue with a little more detail on what you envision.

**Comment by flowerornament** [comment]
@leobauza build script here: https://github.com/urbit/urbit.org/blob/master/scripts/build

**Comment by leobauza** [comment]
@msutherl definitely interested in helping out on low-level stuff like this, I'll try to make some issue re: ideas around how the site's html/css/js structure could be changed in the next iteration for discussion. Not sure I can contribute to urbit in any other way atm

**Comment by flowerornament** [comment]
@leobauza definitely interested to work with you on this! I'll write up some issues when I have a chance in the next couple of days.

Also, I just realized there's a bug in that script – working on it and will update.

**Comment by jfranklin9000** [comment]
```
cp -r $1static-site $2/home/web
```
should be
```
cp -r $1/static-site $2/home/web
```
?

**Comment by flowerornament** [comment]
@jfranklin9000 good catch!

**Comment by flowerornament** [comment]
@leobauza @jfranklin9000 finally got this debugged https://github.com/urbit/urbit.org/blob/master/scripts/build

**Pull request merged**
