### PR TITLE
enable arrays for mentors and champions

### PR DESCRIPTION
**Pull request by thelifeandtimes**

### CODE REVIEW

**Comment by thelifeandtimes** [comment]
@matildepark build issues here.

**Comment by matildepark** [comment]
As of #1739 assignees look like arrays eg. `["person1", "person2"]`.

**Comment by thelifeandtimes** [comment]
> As of #1739 assignees look like arrays eg. `["person1", "person2"]`.

and per my change I take it this doesn't work for champions?

**Comment by matildepark** [comment]
First, you did it like `["person1, person2"]` but it's two quoted names, comma-separated. Second, no, champions aren't currently set up that way.

**Comment by thelifeandtimes** [comment]
would that be simple to implement?

**Comment by thelifeandtimes** [comment]
@gordoncc this should be ready for review and merging

**Comment by thelifeandtimes** [comment]
@thomasurbit met with the gather grantees and they are going to make further changes, so pulled the grant content out of this PR. merging should just add the mentor/champions as array feature.

**Review by gordoncc — APPROVED** [review]

**Pull request merged**
