### PR TITLE
[Grant] Norwegian translation

### PR DESCRIPTION
**Pull request by AndreasAtakan**
#### Ready for review

This is the pull request for my Urbit Grant: [Translate key parts of Urbit.org into Norwegian](https://grants.urbit.org/proposals/1227012285)

My translation has been implemented in a similar manner as @tomholford 's grant 'Translate key parts of Urbit.org into Spanish'.  
I have added my Norwegian translation as a language-pack in Zola.
Thank you Tom, for your help with implementing my translations! (Tom's [pull request](https://github.com/urbit/urbit.org/pull/607))

An overview of my work:
- Introduction – I was not able to implement this translation in Zola, since it seems the page content is hard-coded into the template. However, I have added the translation of the content to `content/understanding-urbit/introduction.no.txt` so it can be used at a later date
- Urbit OS – Finished and implemented in Zola
- Urbit ID – Finished and implemented in Zola
- Interface – Finished and implemented in Zola
- Roadmap: OS1-> OS N – Finished and implemented in Zola
- People + History – Finished and implemented in Zola
- Install + Setup – I have translated the entire `getting-started/` section and implemented it in Zola

### CODE REVIEW

**Comment by AndreasAtakan** [comment]
Ready for review @jalehman and @mikeosborne

**Review by AndreasAtakan — COMMENTED** [review]
Code is finished and ready for final review.

**Review by AndreasAtakan — COMMENTED** [review]
^^

**Comment by hacful-tonteg** [comment]
This is an absolute thrash translation. Did you think no one would notice that you just ran the original text through google translate? Disappointing to see people try to take advantage of the urbit community at this early stage. 

[Here](https://github.com/urbit/urbit.org/pull/621/files#diff-46aedcd73f25ded1a7f4a126d99d9a15a745f3eb2bac09d37433c5297f093a39R39) you can see "your" translation and [here](https://translate.google.com/?sl=auto&tl=no&text=Presentations%20and%20guided%20group%20discussions%20are%20great%20ways%20to%20share%20ideas.%20If%20you%20have%20a%20speaker%20for%20your%20event%2C%20coordinate%20ahead%20of%20time%20and%20make%20sure%20they%20have%20everything%20they%20will%20need%20to%20make%20a%20great%20presentation%20and%20ask%20them%20to%20arrive%20early%20to%20the%20event.%20If%20you%20have%20a%20speaker%2C%20be%20sure%20to%20record%20the%20talk%20so%20that%20it%20can%20be%20posted%20online.%0A%0A&op=translate) is the output from google translate.

The automatic translation does not make any sense and given the high English proficiency rate of Norwegians publishing this non-sensical, low quality text would only make the project seem like a scam.

**Comment by AndreasAtakan** [comment]
I’m very sorry to read this verdict.
It was never my intention to take advantage of this grant project.
I am perfectly willing to redo the translation, and I’m hoping you are able to give me one more go.

**Comment by mikeosborne** [comment]
We're going to pass on this PR.

**Pull request closed without merging**
