### PR TITLE
Ed/btc event template plus post

### PR DESCRIPTION
**Pull request by urcades**
Posting this PR for viewing preview, should probably be merged in after tyler's work is merged, since it's based off his fork.

### CODE REVIEW

**Comment by urcades** [comment]
@tylershuster this is loosely ready to go pending successful merging of your PR (which this PR is based on) and discussion on how to make pages like this a replicable pattern — it's rather ugly, I have to say, and I was encountering a ton of issues in getting css specificity and targeting to work as expected.

Writing it down here as a note and less an actionable request, but I really think we need to drastically update how we handle styling for urbit.org.

**Comment by tylershuster** [comment]
Absolutely. I really would like to convert the whole thing to React

**Comment by tylershuster** [comment]
This should be ready to go after master merged back in

**Comment by urcades** [comment]
@tylershuster + @jalehman  after merging into master, still seeing failing checks across the board – any ideas on what might be causing this?

**Comment by tylershuster** [comment]
Hm...those events should have been deleted.

**Comment by urcades** [comment]
seeing this after trying to get zola to start:

```
Error: Failed to render content of /Users/ed/Urbit/urbit.org/content/docs/glossary/azimuth.md
Reason: Relative link @/getting-started.md not found.
```

**Comment by urcades** [comment]
> Hm...those events should have been deleted.

which events in particular?

**Comment by tylershuster** [comment]
```
12:25:55 PM: zola
12:25:56 PM: Building site...
12:25:56 PM: Failed to build the site
12:25:56 PM: Error: Found path collisions:
12:25:56 PM: - `/events/after-hours-office-hours/` from files ["events/2017-05-25-after-hours-office-hours.md", "events/2017-06-21-after-hours-office-hours.md", "events/2017-03-23-after-hours-office-hours.md"]
12:25:56 PM: - `/events/after-hours-its-just-a-party-man/` from files ["events/2017-12-20-after-hours-its-just-a-party-man.md", "events/2018-12-20-after-hours-its-just-a-party-man.md"]
```

**Comment by urcades** [comment]
now getting a totally different error after pulling:

```
Error: Failed to render page '/Users/ed/Urbit/urbit.org/content/faq.md'
Reason: Failed to render 'page_indiced.html'
Reason: Variable `page.toc` not found in context while rendering 'page_indiced.html'
```

Absolutely no idea where these errors are coming from – I didn't touch these files

**Comment by tylershuster** [comment]
Uh, honestly I would just re-PR. Looks like your changes are simple enough to copy-paste

**Comment by urcades** [comment]
Please refer to #593 !

**Comment by jalehman** [comment]
Beat me to it—thanks!

—

~wolref-podlex
https://urbit.org ( https://urbit.org/ )

**Pull request closed without merging**
