### PR TITLE
fix cli install instructions & restructure

### LINKED ISSUE #1959: Getting started curl links don't work
The getting started links for the linux binaries don't work.

See: https://urbit.org/getting-started/cli

I tried curl -L https://urbit.org/install/linux-aarch64/latest | tar xzk --strip=1 && ./urbit and it both the download and ./urbit fail.

We shouldn't have merged this without testing.

Related: https://github.com/urbit/urbit.org/pull/1943

### PR DESCRIPTION
**Pull request by tinnus-napbus**
Fixes #1959

### CODE REVIEW

**Comment by tinnus-napbus** [comment]
re: #1959

@jalehman @mcevoypeter @matthew-levan

I've added a commit to this pr to fix the install commands & rename the file to just `urbit`. I don't have a mac to test that the `-s` tar options works correctly - can someone with a mac try that & confirm?

**Comment by sigilante** [comment]
LGTM but I also cannot test.

**Comment by zalberico** [comment]
The macOS one is just hanging for me with the following output:
```
❯ curl -L https://urbit.org/install/macos-x86_64/latest | tar xzk -s '/.*/urbit/g' && ./urbit
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    93    0    93    0     0    564      0 --:--:-- --:--:-- --:--:--   577
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
Nothing happens at that point until I control-c to kill it.

**Comment by zalberico** [comment]
```
curl -L https://urbit.org/install/macos-x86_64/latest | tar xzk -s '/.*/urbit/' && ./urbit
```
Worked (removing the /g)

**Review by zalberico — COMMENTED** [review]
Tested macOS, others tested linux, approving and we should merge since current website instructions don't work.

**Pull request merged**
