### PR TITLE
add ecosystem section

### LINKED ISSUE #1642: Ecosystem Pages
See designs in Urbit.org Figma

### PR DESCRIPTION
**Pull request by matildepark**
Fixes #1642 

Adds layouts for the ecosystem section featuring organisations, marketplaces, applications, podcasts, and a monthly spotlight. 

Showcases the spotlight content in custom cards on the front page.

Organization, podcast, marketplace pages all bidirectionally link when mentioned in a spotlight.

Ecosystem spotlights, because they need to render differently in different places, are far more table-like than post-like. Please see the following as a reference:

```
+++
// title just needs to be month
title = "June 2022"

// date required for sorting
date = "2022-06-01"

// featured sections aren't enforced in threes, but might produce weird layout
[featured-1]
title = "Urbit.live"

// description is used on index page for the card
description = "One line about the thing"

type = "Marketplace" // should be Marketplace, Application, Organization, Podcast

// images should be card-sized and will be sized down and filled as a cover in the icon'd, main ecosystem page
image = "https://s3.us-east-1.amazonaws.com/haddefsigwen1/reciprocal/2022.5.20..19.52.50-B137D4AA-DA9E-4B07-98CE-C001C576C7CA_1_201_a.jpeg"

URL = "https://urbit.live"

// content is parsed as markdown, but needs to be inputted here instead as a long-form string, using triple quotes
content = """
This layer 1 marketplace is all the rage.

Let this be a lesson to you."""

[featured-2]
title = "Reciprocal Ltd."
description = "One line about the thing"
type = "Organization"
image = "https://media.urbit.org/site/ecosystem/podcasts/full_1639502000-artwork.jpg"
URL = "https://reciprocal.ltd"
content = """
A design consultancy and friend network.

Let this be a lesson to you."""

[featured-3]
title = "Reciprocal Ltd."
description = "One line about the thing"
type = "Organization"
image = "https://media.urbit.org/site/ecosystem/podcasts/full_1639502000-artwork.jpg"
URL = "https://reciprocal.ltd"
content = """
A design consultancy and friend network.

Let this be a lesson to you."""
+++
```

Please take this and fill it with content (removing obvious sample content when necessary).

### CODE REVIEW

**Comment by gordoncc** [comment]
Posting here for posterity.

This is looking really good so far.

So, I know I said hold off on groups but I overlooked the fact that groups could be linked in the same way as apps.

So let's hold off on a groups index, but let's make them appear on organization pages the same way as applications.

**Comment by gordoncc** [comment]
One other small thing – the newsletter sign up should only live on the Spotlight page, not the other indexes.

**Comment by matildepark** [comment]
> One other small thing – the newsletter sign up should only live on the Spotlight page, not the other indexes.

newsletter CTA is just on the one page? or is the ecosystem newsletter yet another newsletter?

**Comment by gordoncc** [comment]
> > One other small thing – the newsletter sign up should only live on the Spotlight page, not the other indexes.
> 
> newsletter CTA is just on the one page? or is the ecosystem newsletter yet another newsletter?

Yes, just on the spotlight page.  It's Urbit Monthly, the original newsletter.

**Review by gordoncc — COMMENTED** [review]
There are some mobile issues with flexbox on the podcasts pages.
Screen Shot 2022-07-20 at 5 23 05 PM

**Comment by gordoncc** [comment]
Also is there a way we can truncate the titles of the podcasts at like two lines?  The truncate tailwind class yields odd behavior.

Might be a better idea to give up the 2-col layout here and just make this a single column list.

**Comment by matildepark** [comment]
> Also is there a way we can truncate the titles of the podcasts at like two lines? The truncate tailwind class yields odd behavior.
> 
> Might be a better idea to give up the 2-col layout here and just make this a single column list.

Just pushed something — try that out.

**Comment by gordoncc** [comment]
No launch this week, but we're getting there.  Here are some fixes to sort.

- [x] - Make applications into two-col list, fix image shrinking and centering issue on smaller screen widths
- [x] - Sort podcasts by date (latest first)
- [x] - Add links from org name on applications to org page (e.g. quartus and reciprocal on channel page)
- [x] - Add hover state (e.g. opacity .9) on list items
- [x] - Index cards should link to anchor tags on spotlight page for respective sections

**Comment by gordoncc** [comment]
Feature Request - Spotlight featured items linked to content.

Featured items in ecosystem spotlight should be associated with individual ecosystem listing pages via title or id or something, and automatically pull in 
- Image icon
- Ecosystem listing type (org, application, etc)

There should remain a custom image URL that is used for the card image, if there is none then the icon image is used there

The featured item title and icon image should link to the respective org, podcast, or application listing page.

**Comment by gordoncc** [comment]
There's an issue displaying applications that only use bg colors on org pages – see Tlon's page

 
image

**Comment by gordoncc** [comment]
still issues with the application tiles on org pages - now they overlap and the text isn't centered

image

**Comment by gordoncc** [comment]
There's an issue displaying spotlight posts of apps that just use a bg color rather than an image

Screen Shot 2022-07-27 at 1 22 14 PM

**Comment by matildepark** [comment]
Can you push this so I can reproduce?

**Comment by gordoncc** [comment]
Pushed

**Comment by gordoncc** [comment]
Allllmost there.  Spotlight archives aren't displaying the icon images
Screen Shot 2022-07-27 at 3 53 45 PM
.

**Comment by jalehman** [comment]
Mobile nav menu gets hidden by the footer. 

https://user-images.githubusercontent.com/550978/181392802-85542944-1dd1-4322-8a1d-65febf40e01b.MOV

**Review by gordoncc — APPROVED** [review]
Let's go

**Pull request merged**
